name: NodeJS with Grunt

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
1#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      working-directory: contract_library
      run: |
        npm install
    - run: yarn --ignore-scripts
      shell: bash
    - name: Create local node and deploy
      run: |
        yarn hardhat node &
        yarn hardhat run scripts/deploy.ts --network localhost
    - name: Run Tests
      run: yarn hardhat test
    - uses: crytic/slither-action@v0.3.0